# Site settings
title: Playground
email: torstein.norendal@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://torsteinnorendal.net" # the base hostname & protocol for your site
twitter_username: tornoren
github_username:  tornoren

# Build settings
markdown: kramdown
